### ISSUE TITLE
[PUPITRE] Erreur lors du test de la clé USB

### ISSUE THREAD

**Issue by devdevdavid2** [devdevdavid2/Pascal-Project#2]
> Originellement publié ici : https://github.com/Devdevdavid/Pascal-Project/issues/26#issue-1081261885

Lors de la vérification de la présence de dossier dans `/media`, erreur possible (création de plusieurs dossiers liés à une clé USB)
Besoin de réarranger le code et ajouter des sécurités sur cette partie de code.

https://github.com/devdevdavid2/Pascal-Project/blob/9bbaf8dfd8b3efc912eb12365ec3eadc99b63ac5/pupitre_achdr/achdr_main_app.py#L292-L297

**Comment by devdevdavid2** [comment]
https://github.com/devdevdavid2/Pascal-Project/blob/9bbaf8dfd8b3efc912eb12365ec3eadc99b63ac5/pupitre_achdr/achdr_main_app.py#L293

Ce test revient à tester si `/media/pi/VIDEO_ACHDR/1` existe.
Or de ce que je comprends, ce test est là pour détecter si `/media/pi/VIDEO_ACHDR1/` existe. (Le `/` est à la mauvaise place)
Auquel cas on effectue la procédure de redémarrage pour n'avoir que `/media/pi/VIDEO_ACHDR/`.

@bastian-bou : Quels-sont les symptômes du dysfonctionnement observé ?

**Comment by bastian-bou** [comment]
Résolu dans le commit e2c0f40
Testé sur cible (dossier VIDEO_ACHDR supprimé -> redémarrage -> test des boutons vidéo/ppt/manuel/menu)
